server:
  port: 9200

spring:
  application:
    name: elasticsearch-demo
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: docker-cluster
      cluster-nodes: 192.168.139.129:9300